[package]
name = "stmelf-demo"
version = "0.1.0"
authors = ["Johannes Renoth <johannes.renoth@gmx.de>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17.4"
wasm-bindgen = "0.2.68"
